package com.jss.ftp.comons;

public enum FtpStatus {
	CREATE_DIRECTORY_SUCCESS,CREATE_DIRECTORY_FAIL,UPLOAD_FILE_SUCCESS,UPLOAD_FILE_FAIL,DIRECTORY_EXIST,DOWNLOAD_FILE_SUCCESS,DOWNLOAD_FILE_FAIL,REMOTE_FILE_NOEXIST;

}
